---

# To see the different profiles available, run the following on the target host
#
# RHEL 8:
# oscap info /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
#
# RHEL 9:
# oscap info /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml

- name: Perform CIS scan using OpenSCAP
  hosts: "{{ hostlist | default('all') }}"
  become: true
  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_cis

  tasks:
    - name: Define policy
      ansible.builtin.set_fact:
        oscap_policy: "ssg-rhel{{ ansible_facts.distribution_major_version}}-ds"
      when: ansible_facts.distribution is defined and ansible_facts.distribution == "RedHat" and ansible_facts.distribution_major_version is defined and ansible_facts.distribution_major_version != "6"

    - name: Print policy
      ansible.builtin.debug:
        msg: "Scanning for profile {{ oscap_profile }} using policy {{ oscap_policy }} on host {{ inventory_hostname }}"

    - name: Ensure OpenSCAP software is installed (install workbench if desired)
      ansible.builtin.package:
        name: "{{ pkg_list }}"
      vars:
        pkg_list:
          - openscap-scanner
          - scap-security-guide
#          - scap-workbench

    - name: Run OpenSCAP scan and generate report
      ansible.builtin.command: oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results /tmp/oscap.xml \
        --report /tmp/oscap-report.html \
        --fetch-remote-resources \
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml
      ignore_errors: True

    - name: Generate Ansible remediation playbook from the report
      ansible.builtin.command: oscap xccdf generate fix --fix-type ansible \
        --profile {{ oscap_profile }} \
        --output /tmp/ospp-remediations.yml \
        /tmp/oscap.xml

    - name: Download report
      ansible.builtin.fetch:
        src: /tmp/oscap-report.html
        dest: ./oscap-reports/{{ inventory_hostname }}.html
        flat: yes

    - name: Download remediation playbook
      ansible.builtin.fetch:
        src: /tmp/ospp-remediations.yml
        dest: ./oscap-reports/{{ inventory_hostname }}-remediation.yml
        flat: yes
