---
- name: Check compliance against the U.S. Government Commercial Cloud Services (C2S) baseline
  hosts: "{{ vm_fq_hostname | default('') }}"
  become: true

  tasks:
    - name: Run C2S role
      import_role:
        name: RedHatOfficial.rhel7_c2s
